# Generated by Django 3.0.8 on 2020-08-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meduser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=70)),
                ('subject', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('responded', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
