# Generated by Django 3.0.8 on 2020-08-26 12:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meduser', '0002_contactmessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessages',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmessages',
            name='edited_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
