# Generated by Django 3.0.8 on 2020-08-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meduser', '0003_auto_20200826_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessages',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
