# Generated by Django 3.0.8 on 2020-08-15 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lend_and_returns.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meduser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=lend_and_returns.models.increment_invoice_number, max_length=100, null=True)),
                ('type', models.CharField(choices=[('in', 'In'), ('out', 'Out')], max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('edited_date', models.DateTimeField(auto_now=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('company', models.ForeignKey(blank=True, default=lend_and_returns.models.setCompany, null=True, on_delete=django.db.models.deletion.CASCADE, to='meduser.Company')),
                ('currency', models.ForeignKey(blank=True, default=lend_and_returns.models.setCurrency, null=True, on_delete=django.db.models.deletion.CASCADE, to='meduser.Currency')),
            ],
            options={
                'verbose_name_plural': 'Invoices',
            },
        ),
        migrations.CreateModel(
            name='LendOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=lend_and_returns.models.increment_order_number, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('returned_date', models.DateTimeField(blank=True, null=True)),
                ('edited_date', models.DateTimeField(auto_now=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('returned_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending for return'), ('returned', 'Returned'), ('cancel', 'Cancelled')], max_length=20)),
                ('company', models.ForeignKey(blank=True, default=lend_and_returns.models.setCompany, null=True, on_delete=django.db.models.deletion.CASCADE, to='meduser.Company')),
                ('currency', models.ForeignKey(blank=True, default=lend_and_returns.models.setCurrency, null=True, on_delete=django.db.models.deletion.CASCADE, to='meduser.Currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lend',
            },
        ),
        migrations.CreateModel(
            name='LendLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('edited_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending for return'), ('returned', 'Returned'), ('cancel', 'Cancelled')], max_length=20)),
                ('company', models.ForeignKey(blank=True, default=lend_and_returns.models.setCompany, null=True, on_delete=django.db.models.deletion.CASCADE, to='meduser.Company')),
                ('currency', models.ForeignKey(blank=True, default=lend_and_returns.models.setCurrency, null=True, on_delete=django.db.models.deletion.CASCADE, to='meduser.Currency')),
                ('lend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lend_and_returns.LendOrder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meduser.Products')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lend lines',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('company', models.ForeignKey(blank=True, default=lend_and_returns.models.setCompany, null=True, on_delete=django.db.models.deletion.CASCADE, to='meduser.Company')),
                ('currency', models.ForeignKey(blank=True, default=lend_and_returns.models.setCurrency, null=True, on_delete=django.db.models.deletion.CASCADE, to='meduser.Currency')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lend_and_returns.Invoice')),
                ('lend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lend_and_returns.LendOrder')),
                ('lend_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lend_and_returns.LendLine')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meduser.Products')),
                ('user_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Invoice lines',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='lend_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lend_and_returns.LendOrder'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
