# Generated by Django 3.0.8 on 2020-08-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lend_and_returns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='type',
            field=models.CharField(choices=[('in', 'In'), ('out', 'Out')], default='in', max_length=20),
        ),
        migrations.AlterField(
            model_name='lendline',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending for return'), ('returned', 'Returned'), ('cancel', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='lendorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending for return'), ('returned', 'Returned'), ('cancel', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
