# Generated by Django 3.0.8 on 2020-08-17 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lend_and_returns', '0002_auto_20200817_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendline',
            name='lend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lendline', to='lend_and_returns.LendOrder'),
        ),
    ]
