# Generated by Django 3.0.8 on 2020-08-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lend_and_returns', '0004_auto_20200819_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendorder',
            name='complete',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lendorder',
            name='order_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lendorder',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lendline',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending for return'), ('pending_approval', 'Requested return'), ('returned', 'Returned'), ('cancel', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='lendorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending for return'), ('pending_approval', 'Requested return'), ('returned', 'Returned'), ('cancel', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
