# Generated by Django 3.0.8 on 2020-08-25 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lend_and_returns', '0005_auto_20200825_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
