# Generated by Django 3.0.8 on 2020-08-25 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lend_and_returns', '0006_invoice_total_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendorder',
            name='total_received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
