# Generated by Django 3.0.8 on 2020-08-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lend_and_returns', '0003_auto_20200818_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendline',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending for return'), ('pending_approval', 'Pending for approval'), ('returned', 'Returned'), ('cancel', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='lendorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending for return'), ('pending_approval', 'Pending for approval'), ('returned', 'Returned'), ('cancel', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
